const tests = [
  {
    id: 1,
    testId: 1,
    type: "css",
    name: "css test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "css",
  },
  {
    id: 2,
    testId: 2,
    type: "css",
    amount: 25,
    description: "describing",
    name: "css test 2",
    difficulty: "Junior",
    skills: "css",
  },
  {
    id: 3,
    testId: 1,
    type: "git",
    name: "git test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "git",
  },
  {
    id: 4,
    testId: 2,
    type: "git",
    amount: 25,
    description: "describing",
    name: "git test 2",
    difficulty: "Junior",
    skills: "git",
  },
  {
    id: 5,
    testId: 1,
    type: "html",
    name: "html test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "HTML",
  },
  {
    id: 6,
    testId: 2,
    type: "html",
    amount: 25,
    name: "html test 2",
    description: "describing",
    difficulty: "Junior",
    skills: "HTML",
  },
  {
    id: 7,
    testId: 1,
    type: "javaScript",
    name: "javaScript test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "javaScript",
  },
  {
    id: 8,
    testId: 2,
    type: "javaScript",
    amount: 25,
    name: "javaScript test 2",
    description: "describing",
    difficulty: "Junior",
    skills: "javaScript",
  },
  {
    id: 9,
    testId: 1,
    type: "react",
    name: "react test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "react",
  },
  {
    id: 10,
    testId: 2,
    type: "react",
    amount: 25,
    name: "react test 2",
    description: "describing",
    difficulty: "Junior",
    skills: "react",
  },
  {
    id: 11,
    testId: 1,
    type: "typeScript",
    name: "typeScript test 1",
    description: "describing",
    amount: 20,
    difficulty: "Junior",
    skills: "typeScript",
  },
  {
    id: 12,
    testId: 2,
    type: "typeScript",
    amount: 25,
    name: "typeScript test 2",
    description: "describing",
    difficulty: "Junior",
    skills: "typeScript",
  },
];

export default tests;
